sudo: false
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

env:
  matrix:
    - DJANGO="1.11"
    - DJANGO="2.1"
    - DJANGO="2.2"
    - DJANGO="3.0"
    - DJANGO="master"

install: pip install tox-travis
script: tox

matrix:
  fast_finish: true

  include:
    - python: "2.7"
      env: DJANGO="1.11"
    - python: "3.4"
      env: DJANGO="1.11"

  allow_failures:
    - python: "3.6"
      env: DJANGO="master"
    - python: "3.7"
      env: DJANGO="master"
    - python: "3.8"
      env: DJANGO="master"
    - python: "3.9"
      env: DJANGO="master"
    - python: "3.9"
      env: DJANGO="3.0"
    - python: "3.9"
      env: DJANGO="master"

  exclude:
    - python: "3.4"
      env: DJANGO="2.1"
    - python: "3.4"
      env: DJANGO="2.2"
    - python: "3.4"
      env: DJANGO="3.0"
    - python: "3.4"
      env: DJANGO="master"

    - python: "3.5"
      env: DJANGO="2.2"
    - python: "3.5"
      env: DJANGO="3.0"
    - python: "3.5"
      env: DJANGO="master"

    - python: "3.8"
      env: DJANGO="1.11"
    - python: "3.8"
      env: DJANGO="2.0"
    - python: "3.8"
      env: DJANGO="2.1"

    - python: "3.9"
      env: DJANGO="1.11"
    - python: "3.9"
      env: DJANGO="2.0"
    - python: "3.9"
      env: DJANGO="2.1"
    - python: "3.9"
      env: DJANGO="2.2"
